### ISSUE TITLE
It fails to sort a grouped data frame

### ISSUE THREAD

**Issue by holgerbrandl** [Kotlin/dataframe#161] opened 2022-08-28 14:39 UTC
When running
```kotlin
irisData.groupBy("Species").sortBy("Sepal.Length")
```
it fails with 
```
java.lang.IllegalStateException: Can not use ColumnGroup as sort column
```

However, sorting by group is a common usecase. In particular in combination with next() and prev()

**Comment by koperagen** [comment] 2022-08-31 18:37
Thank you for the report! It looks like a bug, because this seems to be working fine:
```
irisData.groupBy("Species")
        .sortBy { it["Petal.Length"] }
```
> In particular in combination with next() and prev()
Can you elaborate?

**Comment by holgerbrandl** [comment] 2022-09-02 15:05
I'm happy to help but I'm unsure about what you would need. It seems, you can reproduce the problem already?

**Comment by koperagen** [comment] 2022-09-02 15:11
Yes, i can reproduce the problem. I don't understand how and when one could use next() and prev() in sorting though.  So i'm curious about the use case and maybe an example?

**Comment by holgerbrandl** [comment] 2022-09-05 05:50
One use case that comes to mind are tool-state changes (ie. in manufacturing). Tools periodically change their status (idle, productive, maintenance, etc.). Later one, one may want to compute the duration for which each tool is in a specific state. To do s, we need to 
```
toolEvents.groupBy("tool_id").sortedBy("timestamp").add("state_duration"){ last timestamp - current).aggregate ... plot...
```

Unfortunately I do not have shareable example data at the moment.

**Comment by koperagen** [comment] 2022-09-06 12:21
I really like this example, thank you.

**Comment by Jolanrensen** [comment] 2022-12-09 12:38
fixed and merged!

**Closed by Jolanrensen** 2022-12-09 12:38 UTC
