### ISSUE TITLE
Failure to convert JSON document

### ISSUE THREAD

**Issue by iamsteveholmes** [Kotlin/dataframe#125] opened 2022-07-05 23:24 UTC
I could swear I found this example somewhere but was unable to find it.  But It seems like this should be readable:
<img width="1456" alt="Screen Shot 2022-07-05 at 4 01 22 PM" src="https://user-images.githubusercontent.com/92353/177432810-ae944ca6-5bd0-491c-bba6-3f7a3ccd3428.png">

If you look at the CSV data the library can read it fine.

**Comment by koperagen** [comment] 2022-07-06 01:14
Hi! Thank you for the report :) From what I see, it seems that the problem is with table rendering. It's hard to propose a viable workaround here. I think it should work fine if you write `ds.print()` instead of `ds`, so you get an ASCII table instead of HTML. Anyway, i'll look this bug tomorrow

**Comment by koperagen** [comment] 2022-07-06 19:27
The fix is in version `0.9.0-dev-1061`, but it might not resolve yet. It usually takes several hours for a new version to be fully published in the maven repository.

**Closed** 2022-07-25 11:17 UTC
